### ISSUE TITLE
[Feature Request] Support for backpacks-like items

### ISSUE THREAD

**Issue by Akeboshiwind** [Vendare/DarkHeresy2E-FoundryVTT#45] opened 2021-03-17 21:17 UTC
Some bits of gear like Backpacks & Combat Vests or other bit of Gear that increases your encumbrance.

The workaround currently is just to add a negative weight for the gear, but it's a bit clunky as you have to subtract the weight of the item from the gained encumbrance.

It would be nice to have an "official" way to do this.

**Comment by Vendare** [comment] 2022-12-16 22:53
duplicate of #3

**Closed by Vendare** 2022-12-16 22:53 UTC
Labels: duplicate, enhancement
