### ISSUE TITLE
Adding, Removing, and Editing Skills

### ISSUE THREAD

**Issue by jangowolf** [Vendare/DarkHeresy2E-FoundryVTT#55] opened 2021-04-26 23:47 UTC
I am wondering if you will update the sheet to allow someone to add, remove, or edit skills. I am running a game using a homebrewed Dark Heresy Rulebook. The only difference between the character sheets are the skill names and the rules that would affect the roll math are a -20 from having a untrained skill. I have already adjusted the later. 

https://docs.google.com/document/d/1g7xbPXrll72i6xpXMkkPsVNBbmFw74cm1w-fUOa--b8/edit#

I like the character sheet and it's features a lot. Thanks for making it.

**Comment by Vendare** [comment] 2022-12-16 22:52
Duplicate of #24

**Closed by Vendare** 2022-12-16 22:52 UTC
Labels: duplicate, enhancement
