### ISSUE TITLE
[Feature Request] Sheet Tab or Alternative Sheet for Vehicles

### ISSUE THREAD

**Issue by Rhodes62** [Vendare/DarkHeresy2E-FoundryVTT#91] opened 2022-12-12 22:18 UTC
A basic Character sheet or Sheet Tab for Vehicles. Somewhere to put their Type, Structural Integrity, their own Front/Side/Rear Armor, Cruising Speed, Tactical Speed, Maneuverability (maybe even make it an automatic button for Operate Tests), Size, Crew, Carrying Capacity and Weapons (and whether they are turrets, sponsons, fixed, etc and their facing. 

Hopefully it isn't too elaborate. Please and Thank you! 

P.S. Not for my purposes, but others might also like a dropdown box that can change a Vehicle Tab/Sheet for Rogue Trader type stat blocks for voidcraft and planetary craft with their somewhat different stat blocks.

**Comment by Vendare** [comment] 2022-12-15 05:11
duplicate of #30

**Closed by Vendare** 2022-12-15 05:11 UTC
Labels: duplicate, enhancement
